resolver: lts-18.25
packages:
- '.'

# extra-deps:
# - X11-xft-0.3.1
# - X11-1.8

flags: {}

extra-package-dbs: []

# allow-newer: true
nix:
    enable: true
    # pure: false
    packages: [ xorg.libX11, xorg.libXrandr, xorg.libXext, pkgconfig, xorg.libXft ]
